nav:
  - PHP: PHP/index.md
  - Evode: Evode/index.md
  - SQL: SQL/01_index.md
  - Java: Java/index.md
  - JQuery: jquery/index.md
  - TypeScript: typescript/index.md
  - React: react/index.md
  - NextJS: NextJS/index.md
  - Docker: docker/index.md
  - Git: git/index.md
  - GitHubAction: GitHubAction/index.md
  - Homelab: homelab/index.md

site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
