nav:
  - Git: git/index.md
  - Linux:
      - Commandes: linux/commande.md
      - Gestion des droits: linux/droitAcces.md
      - Pipe: linux/pipe.md
      - Grep: linux/grep.md
      - WSL: linux/wsl.md
      - Curl: linux/curl.md
      - Old: linux/old.md
  - Go:
      - New: go/index.md
      - Commentaire: go/commentaire.md
      - Affichage: go/affichage.md
      - Saisie: go/saisie.md
      - Variable: go/variable.md
      - Constante: go/constante.md
      - Types: go/types.md
      - Condition: go/condition.md
      - Boucle: go/boucle.md
      - Arithmetique: go/arithmetique.md
      - Binaire: go/binaire.md
      - Fonction: go/fonction.md
      - Old: go/old_index.md
      - Old2: go/old2.md
  - Php:
      - Php: php/index.md
      - Old: php/old.md
  - Symfony: symfony/index.md
  - Evode:
      - Last: evode/index.md
      - Old_version: evode/old_index.md
  - SQL:
      - Requête: sql/request.md
      - Table: sql/table.md
  - Java:
      - Java: java/index.md
      - Types: java/types.md
  - JavaScript:
      - New: javascript/index.md
      - Old: javascript/old.md
  - Jest: jest/index.md
  - JQuery: jquery/index.md
  - TypeScript: typescript/index.md
  - React: react/index.md
  - NextJS: nextJS/index.md
  - Docker: docker/index.md
  - GitHubAction: githubaction/index.md
  - Homelab: homelab/index.md
  - Python:
      - Python: python/index.md
      - Old: python/old.md
      - Fonction: python/fonctions.md
  - C++: c++/index.md
  - Github Action: github_action/index.md
  - IA: ia/index.md
  - C: c/index.md
  - Bun: bun/index.md
  - HTML: html/index.md
  - CSS:
      - Base: css/index.md
      - Formulaire: css/formulaire.md
  - Elysia: elysia/index.md
  - Express: express/index.md
  - Tanstack:
      - TanstackForm: tanstack/tanstackForm.md
      - TanstackRouter: tanstack/tanstackRouter.md
      - TanstackTable: tanstack/tanstackTable.md
      - TanstackQuery: tanstack/tanstackQuery.md
  - Svelte:
      - Svelte: svelte/index.md
  - Rust:
      - Rust: rust/index.md
  - Biome:
      - Biome: biome/index.md
  - Drizzle:
      - Drizzle: drizzle/index.md
  - Fish-Shell:
      - Fish-Shell: fishShell/index.md
  - Mkdoc: mkdocs/index.md
  - Nvim: nvim/index.md
  - Pnpm: pnpm/index.md

site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
