nav:
  - Golang: go/index.md
  - PHP: php/index.md
  - Evode: evode/index.md
  - SQL: 
    - Requête: sql/request.md 
    - Table: sql/table.md
  
  
  SQL/01_index.md
  - Java: Java/index.md
  - JQuery: jquery/index.md
  - TypeScript: typescript/index.md
  - React: react/index.md
  - NextJS: nextJS/index.md
  - Docker: docker/index.md
  - Git: git/index.md
  - GitHubAction: githubaction/index.md
  - Homelab: homelab/index.md
  - Symfony: symfony/index.md
  - Python: python/index.md
  - Curl: curl/index.md
  - Linux:
      - WSL: linux/wsl.md

site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
